# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-14 22:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_auto_20180614_2145'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='view_on_front_page',
            field=models.BooleanField(default=True),
        ),
    ]
