# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-24 16:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0002_auto_20180624_1356'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='first_name',
            new_name='full_name',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='eircode',
            new_name='postcode',
        ),
        migrations.RemoveField(
            model_name='order',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='order',
            name='line_3_of_address',
        ),
        migrations.AddField(
            model_name='order',
            name='country',
            field=models.CharField(default='Ireland', max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='county',
            field=models.CharField(default='Waterford', max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='town_or_city',
            field=models.CharField(default='Tramore', max_length=40),
        ),
    ]
