# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-24 17:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0003_auto_20180624_1613'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='line_1_of_address',
            new_name='street_address1',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='line_2_of_address',
            new_name='street_address2',
        ),
    ]
