# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-24 19:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0004_auto_20180624_1717'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='email_address',
        ),
        migrations.AlterField(
            model_name='order',
            name='country',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='county',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='postcode',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='town_or_city',
            field=models.CharField(max_length=40),
        ),
    ]
