# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-12 01:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0009_auto_20180712_0006'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderlineitem',
            name='status',
            field=models.CharField(choices=[('Awaiting Dispatch', 'Awaiting Dispatch'), ('Dispatched', 'Dispatched'), ('Delivered', 'Delivered')], default=1, max_length=20),
            preserve_default=False,
        ),
    ]
