# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-12 01:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0010_orderlineitem_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderlineitem',
            name='status',
            field=models.CharField(choices=[('AWAITINGDISPATCH', 'Awaiting Dispatch'), ('DISPATCHED', 'Dispatched'), ('DELIVERED', 'Delivered')], default='AWAITINGDISPATCH', max_length=20),
        ),
    ]
