# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-12 01:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0011_auto_20180712_0127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderlineitem',
            name='status',
            field=models.CharField(choices=[('AWAITING DISPATCH', 'Awaiting Dispatch'), ('DISPATCHED', 'Dispatched'), ('DELIVERED', 'Delivered')], default='AWAITING DISPATCH', max_length=20),
        ),
    ]
