# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-12 11:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0013_auto_20180712_0143'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderlineitem',
            name='total',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
