# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-12 01:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=5),
        ),
        migrations.AlterField(
            model_name='review',
            name='would_you_recommend_to_a_friend',
            field=models.BooleanField(choices=[(True, 'YES'), (False, 'NO')], default=True),
        ),
    ]
