# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-12 01:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0002_auto_20180712_0145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='would_you_recommend_to_a_friend',
            field=models.CharField(choices=[('YES', 'YES'), ('NO', 'NO')], default='YES', max_length=3),
        ),
    ]
