# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-21 14:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0003_auto_20180712_0149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='comment',
            field=models.TextField(null=True),
        ),
    ]
