# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-10 20:53
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0003_auto_20180622_1441'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=100)),
                ('review_title', models.CharField(max_length=200)),
                ('comment', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('rating', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')])),
                ('would_you_recommend_to_a_friend', models.BooleanField(choices=[(True, 'YES'), (False, 'NO')])),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('reviewing_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.Product')),
            ],
        ),
    ]
