# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-10 21:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='review_title',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='review',
            name='reviewing_product',
        ),
        migrations.RemoveField(
            model_name='review',
            name='user_name',
        ),
    ]
