"""
Django settings for GinasBeautyStudio project.

Generated by 'django-admin startproject' using Django 1.11.

For more information on this file, see
https://docs.djangoproject.com/en/1.11/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.11/ref/settings/
"""

import os
import dj_database_url
try:
    import env
except ImportError:
    pass

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.11/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

''' Allowed Hosts '''

ALLOWED_HOSTS = [os.environ.get('C9_HOSTNAME'),
                 'ginas-beauty-studio.herokuapp.com']

'''  Installed Apps '''

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django_forms_bootstrap',
    'ckeditor',
    'ckeditor_uploader',
    'home',
    'accounts',
    'posts',
    'products',
    'cart',
    'productsearch',
    'checkout',
    'review',
    'storages',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

''' Root urls '''

ROOT_URLCONF = 'GinasBeautyStudio.urls'

''' Templates '''
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                # needed to serve our media files properly
                'django.template.context_processors.media',
                'cart.contexts.cart_contents',
            ],
        },
    },
]

''' WSGI application '''

WSGI_APPLICATION = 'GinasBeautyStudio.wsgi.application'

''' Database settings '''
# https://docs.djangoproject.com/en/1.11/ref/settings/#databases

if "DATABASE_URL" in os.environ:
    DATABASES = {'default':
                 dj_database_url.parse(os.environ.get('DATABASE_URL'))}
else:
    print("Database URL not found. Using SQLite instead")
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
        }
    }

''' Password validation '''
# https://docs.djangoproject.com/en/1.11/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_'
                'validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_'
                'validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_'
                'validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_'
                'validation.NumericPasswordValidator',
    },
]

''' needed in order to use a customers email address to login '''

AUTHENTICATION_BACKENDS = ['django.contrib.auth.backends.ModelBackend',
                           'accounts.backends.EmailAuth', ]

# Internationalization
# https://docs.djangoproject.com/en/1.11/topics/i18n/

LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_L10N = True
USE_TZ = True

''' AWS settings '''

# caches static files for along time into the future
AWS_S3_OBJECT_PARAMETERS = {
    'Expires': 'Thu, 31 Dec 2099 20:00:00 GMT',
    'CacheControl': 'max-age=94608000',
}
AWS_STORAGE_BUCKET_NAME = 'gina-beauty-studio'
AWS_S3_REGION_NAME = 'eu-west-1'
# while we are running locally we will use the env.py for key values
AWS_ACCESS_KEY_ID = os.environ.get("AWS_ACCESS_KEY_ID")
AWS_SECRET_ACCESS_KEY = os.environ.get("AWS_SECRET_ACCESS_KEY")
AWS_S3_CUSTOM_DOMAIN = '%s.s3.amazonaws.com' % AWS_STORAGE_BUCKET_NAME

''' Static file settings '''

STATICFILES_LOCATION = 'static'
STATICFILES_STORAGE = 'custom_storages.StaticStorage'

STATIC_URL = '/static/'
STATICFILES_DIRS = (
    os.path.join(BASE_DIR, "static"),
    )

''' Media file settings '''

MEDIAFILES_LOCATION = 'media'
DEFAULT_FILE_STORAGE = 'custom_storages.MediaStorage'

MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
MEDIA_URL = "https://%s/%s/" % (AWS_S3_CUSTOM_DOMAIN, MEDIAFILES_LOCATION)

''' session storage for messages '''

MESSAGE_STORAGE = 'django.contrib.messages.storage.session.SessionStorage'


''' Email settings '''

# email encription used by gmail
EMAIL_USE_TLS = True
# a protocol used to send emails
EMAIL_HOST = 'smtp.gmail.com'
# environment variables for host email address
EMAIL_HOST_USER = os.environ.get("EMAIL_ADDRESS")
# environment varriables for host password
EMAIL_HOST_PASSWORD = os.environ.get("EMAIL_PASSWORD")
# the port we will use to send it through
EMAIL_PORT = 587

''' stripe - credit card payment variables '''

# tells Django where to find our stripe publishable key
# and secret key for payments
STRIPE_PUBLISHABLE = os.getenv('STRIPE_PUBLISHABLE')
STRIPE_SECRET = os.getenv('STRIPE_SECRET')

''' settings for CKEDITOR text editor and media uploader
    used during post creations '''

CKEDITOR_UPLOAD_PATH = "uploads/"
CKEDITOR_IMAGE_BACKEND = "pillow"
CKEDITOR_CONFIGS = {
    'default': {
        'skin': 'moono',
        'extraPlugins': 'image2',

        'toolbar_GinasToolbar': [
            {'name': 'basicstyles',
             'items': ['Bold', 'Italic', 'Underline', 'Strike']},
            {'name': 'paragraph',
             'items': ['NumberedList', 'BulletedList', '-', 'Outdent',
                       'Indent', '-', 'JustifyLeft', 'JustifyCenter',
                       'JustifyRight', 'JustifyBlock']},
            {'name': 'links', 'items': ['Link', 'Unlink', 'Anchor']},
            {'name': 'insert',
             'items': ['Image', 'Table',
                       'HorizontalRule',
                       'Smiley', 'SpecialChar']},
            {'name': 'styles',
             'items': ['Styles', 'Format', 'Font', 'FontSize']},
            {'name': 'colors', 'items': ['TextColor', 'BGColor']},
            {'name': 'spellcheck', 'items': ['Scayt']},
            {'name': 'document', 'items': ['Source']},
            {'name': 'maximize', 'items': ['Maximize', ]},
        ],

        'toolbar': 'GinasToolbar',
    }
}
