# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-13 14:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20180622_1441'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='average_rating',
            field=models.IntegerField(null=True),
        ),
    ]
