# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-13 14:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_product_average_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='num_of_ratings',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='average_rating',
            field=models.IntegerField(default=0),
        ),
    ]
