# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-13 15:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20180713_1405'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='average_rating',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=1),
        ),
        migrations.AlterField(
            model_name='product',
            name='num_of_ratings',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=1),
        ),
    ]
